# Generated by Django 4.0.5 on 2023-04-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
