# Generated by Django 4.0.5 on 2023-04-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_myuser_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='points',
        ),
    ]
