# Generated by Django 4.0.5 on 2023-04-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devSide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_file',
            field=models.FileField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_screenshot',
            field=models.FileField(upload_to='media/'),
        ),
    ]
