# Generated by Django 4.0.5 on 2023-04-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devSide', '0002_project_user_num_alter_project_project_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='max_user_num',
            field=models.IntegerField(default=0),
        ),
    ]
