# Generated by Django 4.0.5 on 2023-04-08 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devSide', '0004_favicon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favicon',
        ),
    ]
