# Generated by Django 4.0.5 on 2023-04-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devSide', '0005_delete_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tier',
            field=models.CharField(default='', max_length=20),
        ),
    ]
